// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJFyVCP1P8yPvCu7NTxJUn1eUUFflNcQ',
    appId: '1:722169672929:android:164a81d1dd9e0dbfff33a0',
    messagingSenderId: '722169672929',
    projectId: 'farwa-khalid-ebook-novels',
    storageBucket: 'farwa-khalid-ebook-novels.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcC_QND6a1gwm6bw586Yr39yqrdeqq71c',
    appId: '1:722169672929:ios:d390799c15eb5611ff33a0',
    messagingSenderId: '722169672929',
    projectId: 'farwa-khalid-ebook-novels',
    storageBucket: 'farwa-khalid-ebook-novels.firebasestorage.app',
    androidClientId: '722169672929-11cefkvkjf1jau32d9nscuju8mf71j9e.apps.googleusercontent.com',
    iosClientId: '722169672929-dar0f35i18rb0nlu9s8bfora4bh46u94.apps.googleusercontent.com',
    iosBundleId: 'com.farwa.farwaKhalid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcC_QND6a1gwm6bw586Yr39yqrdeqq71c',
    appId: '1:722169672929:ios:d390799c15eb5611ff33a0',
    messagingSenderId: '722169672929',
    projectId: 'farwa-khalid-ebook-novels',
    storageBucket: 'farwa-khalid-ebook-novels.firebasestorage.app',
    androidClientId: '722169672929-11cefkvkjf1jau32d9nscuju8mf71j9e.apps.googleusercontent.com',
    iosClientId: '722169672929-dar0f35i18rb0nlu9s8bfora4bh46u94.apps.googleusercontent.com',
    iosBundleId: 'com.farwa.farwaKhalid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3BERn2FWhC9iOcau48o9w5Lx9IVXSom8',
    appId: '1:722169672929:web:fd816b13273c93eeff33a0',
    messagingSenderId: '722169672929',
    projectId: 'farwa-khalid-ebook-novels',
    authDomain: 'farwa-khalid-ebook-novels.firebaseapp.com',
    storageBucket: 'farwa-khalid-ebook-novels.firebasestorage.app',
    measurementId: 'G-S89S2VS712',
  );

}